var claves = {
	"setTimeout": "ejecutar funciones despues de un tiempo",
	"prototype": "asignar funciones a una instacia de un objeto",
	"new":"crear una instancia d eun objeto",
	"this": "apuntador al contexto",
	"ninja.age": "asignar atributos a uan isntancia",
	"id": "nombre del input usado por javascript para manipular el DOM",
	"value": "valor d en input",
	"onClick": "evento sobre u elemnto del DOM",
	"parseFloat": "parsear un elemnto de cadena  a float",
	"parseInt": "parsear un elementoa int",
	"global": "variable que se puede usar en cualuqie parte dle codigo",
	"local": "varialbe qu ese puede usar oslo dentor del scope que ha sido delcarado",
	"length": "ver el tamano d euna cadena de texto javascript",
	"substr": "(inicio,final) obtener un subelemento de una cadena javascript",
	"indexOf": "ver en donde se encuentra una cadena (valor,inicio)",
	"lastIndexOf": "busca el index de un carcer pero desde el final",
	"replace":"(texto,reemplazo) permite reemplazar uan caden ade texto por otra",
	"toUpperCase": "cadenas a Mayusculas",
	"toLowerCase": "cadenas aminusculas",
	"DOM": "Document Object Model todos el arbol de document",
	"getElementsByTagName":"acceder a elementos del DOM por tag",
	"getElementById":"elementos por id",
	"createElement": "crear elemento del DOM",
	"createTextNode": "crear noddo de texto",
	"appendChild": "añadir un hijo",
	"setAttribute": "añadir atributos de css3",
	"parentNode": "coje el padre",
	"insertBefore":"(elemento,referencia) agregar antes",
	"innerHTML": "cojer codigo html dentro de una etiqueta",
	"textContent":"solo genera codiog no html5 text dentro etiqueta",
	"replaceChild":"(elemento,remplazo) reemplazr nodos DOM",
	"removeChild":"borrar elemento del DOM",
	".":"accedemos atributos dentro de elementos",
	".className": "acceder a las clases de un elemnto",
	".style.<algo>":"accedemos a los estilos del elemento",
	"replace":"(elemento reemplazo) reemplazar de una cadena de texto",
	"lorempixel.com":"direccion de ocrreo donde se puede conseguir imagenes",
	"eventos":"no usar metodos online no es recomendable",
	"functionAutoejecutable": "(function(){}())",
	"addEventListener":"('evento', function(){});",
	"eventospaginaWeb": "http://www.w3schools.com/jsref/dom_obj_event.asp",
	"focus": "cuando damos click en un input",
	"change": "cuando el input tiene un cambio",
	"removeEventListener": "nos permite eliminar eventos",
	"type": "tipo de evento",
	"target": "donde se aplica el evento",
	"preventDefault": "para evitar el comportamiento por default de un elemento dle DOM",
	"requiere": "en html5 es para que n campo sea requerido desde html5",
	"getElementByName": "conseguir un elemento del DOM por name",
	"callback": "es una funcion que se pasa como parametor para otra funcion",
	"ux":"todas las interacciones que una personas itene con tu porcucto en un tiempo determinado",
	"ui": "user interface",
	"DonaldNorman": "personas UX",
	"Libroux": "100 cosas que sabias saber de la gente",
	"affordances": "propiedasdes del objeto + habilidades dle usuario",
	"significantes": "dicne que hacer y como ",
	"UI patterns" : "patrones de interfacese de usarios",
	"MalChimp" : "servioc par en viar correos masivos",
	"Pattern Library": "libreria que contiene patrones de diseño",
	"Yahoo design patter library": "patrones de diseño con ayhoo",
	"Ios/": "ios7 design resources patrones de diseño tomar ocmo referencia",
	"UIPatterns.com":"Patrones de diseño para intrfaces de usairo",
	"Bootstrap": "front-end framwork responsive design ver por los componentes",
	"Fondattion": "front-end framework",
	"FlatUI": "ver ocmo usar el diseño flat",
	"frameworkUX": "estructural, visual , social , conceptual",
	"wireframe": "funcionalidad, layout, copy(texto) puedne ser dibujos hecho a manos o hechos ocn aplicacoines",
	"mockup": "ya incluyen colore stipografias imagenes como se quiere que quede la app",
	"prototipoUx" : "entneder cual es la navegacion de la paigna y ocmo se va ver en distitos dispositivos",
	"AdobeIllustraitor": "editor de graficos vectoriales",
	"invision": "mejor alternativa que nos permite hacer prototios",
	""









};